import fs from 'fs';
import path from 'path';

const ROOT = path.resolve(process.cwd(), 'e2e');
const SHOTS = path.join(ROOT, 'screenshots');
const REPORTS = path.join(ROOT, 'reports');

if (!fs.existsSync(SHOTS)) fs.mkdirSync(SHOTS, { recursive: true });
if (!fs.existsSync(REPORTS)) fs.mkdirSync(REPORTS, { recursive: true });

export const BUGS_FILE = path.join(REPORTS, 'bugs.md');

function appendBugsHeader() {
  if (!fs.existsSync(BUGS_FILE)) {
    fs.writeFileSync(
      BUGS_FILE,
      `# Bug report — Catieli health-app\n\nGenerated by automated E2E run.\n\n`,
    );
  }
}
appendBugsHeader();

export function recordBug({ flow, severity = 'medium', title, description, screenshot, page }) {
  const ts = new Date().toISOString();
  const lines = [
    `## [${severity.toUpperCase()}] ${flow} — ${title}`,
    `- when: ${ts}`,
    page ? `- page: ${page}` : '',
    screenshot ? `- screenshot: \`${path.relative(ROOT, screenshot)}\`` : '',
    '',
    description,
    '',
  ].filter(Boolean);
  fs.appendFileSync(BUGS_FILE, lines.join('\n') + '\n');
}

export function attachConsoleLogging(page, context = { errors: [], warnings: [], pageerrors: [], requests: [] }) {
  page.on('console', (msg) => {
    const type = msg.type();
    const text = msg.text();
    if (type === 'error') context.errors.push(text);
    else if (type === 'warning') context.warnings.push(text);
  });
  page.on('pageerror', (err) => {
    context.pageerrors.push(`${err.name}: ${err.message}`);
  });
  page.on('requestfailed', (req) => {
    context.requests.push(`FAIL ${req.method()} ${req.url()} :: ${req.failure()?.errorText}`);
  });
  page.on('response', (res) => {
    const status = res.status();
    if (status >= 400) {
      context.requests.push(`${status} ${res.request().method()} ${res.url()}`);
    }
  });
  return context;
}

export async function shot(page, name) {
  const file = path.join(SHOTS, `${name}.png`);
  await page.screenshot({ path: file, fullPage: true });
  return file;
}

export function uniqueEmail(prefix = 'qa') {
  const stamp = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `${prefix}_${stamp}_${rand}@example.com`;
}

export async function waitNetworkIdle(page, ms = 500) {
  try {
    await page.waitForLoadState('networkidle', { timeout: 8000 });
  } catch {
    // best effort
  }
  await page.waitForTimeout(ms);
}
